/**
 * @file types.ts
 * @description Defines shared TypeScript types and interfaces for the application.
 */

/**
 * Represents a single item to be used in a MaxDiff task.
 * This can be an item derived from a text file input or an uploaded media file.
 */
export interface MaxDiffItem {
  /** A unique identifier for the item. */
  id: string;
  /** The type of the item. */
  type: 'text' | 'image' | 'video' | 'audio';
  /** 
   * A user-facing name for the item. 
   * For text items, this will be the text content itself. 
   * For media items, this will typically be the filename.
   */
  name: string;
  /** 
   * Optional. The object URL generated by `URL.createObjectURL()` for 
   * displaying image or video previews. This URL needs to be managed 
   * (i.e., revoked when no longer needed).
   */
  previewUrl?: string;
  /** 
   * Optional. The original `File` object, primarily for media items. 
   * This can be useful if the raw file data needs to be accessed later, 
   * e.g., for storing in IndexedDB or re-uploading.
   */
  file?: File;
  /** 
   * Optional. The actual content for items of type 'text'.
   * Can be redundant if `name` for text items already holds the content.
   */
  textContent?: string;
}

